name: NuGet Generation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet 
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

#  latest image has .NET already installed!
#      - name: Setup .NET environment
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: '2.2.105' 
          
      - name: Build and Publish
        run: |  
          cd WindowsTrayItemFramework
          dotnet build --configuration Release
          dotnet pack -c Release -o out  
          dotnet nuget push "out/*.nupkg"  --api-key ${{ secrets.NUGET_API_KEY }} --source "github"
